language: node_js

node_js:
  - "14"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g eslint


script:
  - npm run build
  - npm run test
  - npm run lint

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*

      deploy:
        provider: script
        skip_cleanup: true
        script:
          - cp package.json lib && cd lib && npx semantic-release
