name: Release
on:
    push:
        branches:
            - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
            -   name: Release
                run: |
                    npm i
                    npm run build 
                    cp package.json lib/package.json
                    cd lib && npx semantic-release
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}